/**
 * Catalogue YA FALY KA - Produits reels avec vraies photos du magasin
 * Grand Mbao, Cite Baye Niasse, Dakar â€” +221 78 564 57 67
 */

const STORE_CONFIG = {
  name: "YA FALY KA",
  tagline: "Mobilier d'Excellence â€¢ Electromenager â€¢ Literie & Confort",
  phone: "+221 78 564 57 67",
  phoneDisplay: "+221 78 564 57 67",
  additionalPhones: ["+221 77 651 75 58", "+221 77 647 12 90", "+221 78 107 49 67"],
  whatsappNumber: "221785645767",
  email: "contact@yafalyka-store.com",
  address: "Grand Mbao, Cite Baye Niasse (Dakar, Senegal)",
  hours: "Tous les jours : 08h30 - 22h30",
  currency: "FCFA",
  tiktokUrl: "https://www.tiktok.com/@globaldecoameublemant?_r=1&_t=ZS-99tOu0NYh4C",
  googleMapsUrl: "https://maps.google.com/?q=Grand+Mbao+Dakar"
};

const IMG = "assets/images/products/";

const PRODUCTS = [
  {
    id: "yfk-bureau-01",
    name: "Chaise de Bureau Ergonomique Mesh avec Appuie-Tete",
    category: "mobilier", categoryLabel: "Chaises & Bureaux",
    price: 65000, oldPrice: 78000,
    badge: "Bestseller", badgeType: "hot",
    rating: 4.9, reviewsCount: 38,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.27.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.35.jpeg",
    shortDesc: "Dossier maille respirante mesh, appuie-tete reglable, pietement chrome 5 branches.",
    description: "Chaise de bureau ergonomique professionnelle avec dossier maille respirante anti-chaleur. Appuie-tete integre reglable. Verin hydraulique classe 3. Structure acier chrome avec roulettes silencieuses tout type de sol.",
    features: ["Dossier maille respirante haute densite","Appuie-tete cervical reglable","Verin hydraulique classe 3 certifie SGS","Pietement chrome 5 branches","Roulettes nylon anti-rayures tous sols"],
    dimensions: "Hauteur: 105-115cm | Assise: 50cm | Charge max: 150 kg",
    stockStatus: "En stock (Livraison immediate)", inStock: true
  },
  {
    id: "yfk-bureau-02",
    name: "Chaise de Bureau Ergonomique Haute Assise Noire",
    category: "mobilier", categoryLabel: "Chaises & Bureaux",
    price: 58000, oldPrice: 72000,
    badge: "Confort Pro", badgeType: "premium",
    rating: 4.8, reviewsCount: 27,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.35 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.27.jpeg",
    shortDesc: "Chaise ergonomique haute avec dossier mesh structure et base plastique noire solide.",
    description: "Chaise de bureau confort avec dossier ergonomique maille respirante et assise rembourrÃ©e. Accoudoirs fixes noirs ergonomiques. Base plastique renforcee tres solide avec roulettes silencieuses.",
    features: ["Dossier maille respirante anti-chaleur","Accoudoirs fixes ergonomiques","Reglage hauteur par verin a gaz","Base plastique renforcee solide","Roulettes silencieuses parquet/carrelage"],
    dimensions: "Hauteur assise: 45-55cm | Largeur: 62cm | Charge max: 120 kg",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-bureau-03",
    name: "Bureau Direction Executif Bois Fonce et Gris",
    category: "mobilier", categoryLabel: "Chaises & Bureaux",
    price: 185000, oldPrice: 220000,
    badge: "Direction", badgeType: "premium",
    rating: 5.0, reviewsCount: 15,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.50.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.50.jpeg",
    shortDesc: "Bureau de direction bois fonce et gris metallique avec rangement et caisson serrure.",
    description: "Bureau direction prestige en finition bois fonce et gris structure. Spacieux plateau avec bandes metal inox brossees. Caisson lateral 3 tiroirs avec serrure. Ideal bureaux professionnels et cabinets.",
    features: ["Plateau melanime bois fonce resistant rayures","Bandes decoratives metal inox brosse","Caisson lateral 3 tiroirs + serrure","Structure metal portante robuste","Dimensions genereuses"],
    dimensions: "140x70x75 cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-01",
    name: "Salon Chesterfield Cuir Noir Royal 1+2+3 Places",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 750000, oldPrice: 900000,
    badge: "Luxe Royal", badgeType: "premium",
    rating: 5.0, reviewsCount: 22,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.38.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.38.jpeg",
    shortDesc: "Ensemble salon chesterfield cuir noir capitonne cristaux, style royal baroque.",
    description: "Ensemble salon de prestige style Chesterfield en cuir synthetique noir. Capitonnage cristaux et motifs baroques sur la tete de canape. Structure bois massif avec pieds sculptes noir. Set complet 1+1+3 places ideal salon ou espace VIP.",
    features: ["Cuir synthetique noir haute qualite","Capitonnage cristaux style chesterfield","Structure bois massif solide durable","Pieds sculptes bois noir","Set 1+1+3 places complet"],
    dimensions: "3 places: 220x90x110cm | 1 place: 110x90x110cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-02",
    name: "Salon Cuir Gris Bordures Or 1+2+3 Places Moderne",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 680000, oldPrice: 820000,
    badge: "Tres Demande", badgeType: "hot",
    rating: 4.9, reviewsCount: 31,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.37 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.37 (2).jpeg",
    shortDesc: "Salon cuir gris anthracite avec liseret orange dore, pieds acier dore, capitons raffines.",
    description: "Ensemble salon contemporain en cuir gris anthracite premium avec touche orange doree sur les cotes. Capitonnage raffine avec boutons. Pieds acier plaque or brushed. Melange parfait elegance moderne et luxe.",
    features: ["Cuir gris anthracite premium","Bordure orange doree signature","Pieds acier dore brushed inoxydable","Cousins mousse haute densite","Set 1+1+3 places complet"],
    dimensions: "3 places: 210x90x90cm | 1 place: 110x90x90cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-03",
    name: "Salon Chesterfield Blanc Ivoire 1+2+3 Places",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 720000, oldPrice: 860000,
    badge: "Elegance Pure", badgeType: "premium",
    rating: 5.0, reviewsCount: 18,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.39.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.39.jpeg",
    shortDesc: "Ensemble salon blanc ivoire capitonne a losanges, style chesterfield moderne pieds dores.",
    description: "Ensemble salon elegance totale simili cuir blanc ivoire. Capitonnage a losanges sur le canape principal. Fauteuils arrondis confortables. Pieds fins acier dore. Raffinement pur dans votre espace de vie.",
    features: ["Simili cuir blanc ivoire anti-taches","Capitonnage losanges canape principal","Fauteuils 1 place accoudoirs arrondis","Pieds fins acier dore 15cm","Set 3 pieces 1+1+3"],
    dimensions: "3 places: 200x85x85cm | 1 place: 90x85x85cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-04",
    name: "Salon Cuir Noir Moderne Carre 1+2+3 Places",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 620000, oldPrice: 750000,
    badge: "Contemporain", badgeType: "hot",
    rating: 4.8, reviewsCount: 25,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.37.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.37.jpeg",
    shortDesc: "Salon moderne cuir noir design geometrique carre avec surpiquures blanches structurantes.",
    description: "Salon contemporain lignes epurees cuir noir mat avec surpiquures blanches structurantes. Design cube moderne assise profonde et confortable. Structure metal cachee ultra-solide.",
    features: ["Cuir synthetique noir mat resistance","Surpiquures blanches structurantes","Design cube contemporain lignes droites","Assise profonde confortable","Structure metal ultra-solide"],
    dimensions: "3 places: 220x90x85cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-05",
    name: "Salon Tissu Bleu Roi 1+2+3 Places",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 580000, oldPrice: 700000,
    badge: "Couleur Tendance", badgeType: "new",
    rating: 4.7, reviewsCount: 16,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.37 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.37 (1).jpeg",
    shortDesc: "Ensemble canape bleu roi vif avec capitons droits et pieds chromes argentes.",
    description: "Salon en tissu bleu roi luxueux pour un interieur dynamique. Rembourrage genereux et moelleux. Pieds chromes argentes. Ideal pour affirmer un style fort.",
    features: ["Tissu velours bleu roi antitache","Capitons reguliers verticaux dossier","Pieds chromes argentes 15cm","Mousse haute densite indeformable","Set 1+2+3 places complet"],
    dimensions: "3 places: 200x90x90cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-06",
    name: "Salon Baroque Blanc Royal Bois Sculpte 1+2+3",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 850000, oldPrice: 1000000,
    badge: "Prestige", badgeType: "premium",
    rating: 5.0, reviewsCount: 11,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.38.01 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.38.01 (1).jpeg",
    shortDesc: "Salon blanc baroque accoudoirs sculptes bois, capitonnage luxueux et clous dores.",
    description: "Magnifique ensemble salon style baroque francais simili cuir blanc creme. Accoudoirs et pieds sculptes bois dore. Clous chromes dores decoratifs. Capitonnage classique sur le dossier.",
    features: ["Simili cuir blanc creme superieur","Accoudoirs pieds bois sculpte or","Clous dores decoratifs accoudoirs","Capitonnage classique dossier","Set 1+1+3 places grandes dimensions"],
    dimensions: "3 places: 240x105x120cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-07",
    name: "Canape Angle Cuir Orange et Blanc en L",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 680000, oldPrice: 800000,
    badge: "Angle XXL", badgeType: "hot",
    rating: 4.8, reviewsCount: 14,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.38 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.38 (1).jpeg",
    shortDesc: "Grand canape d'angle cuir orange et blanc, assise profonde et dossier structure.",
    description: "Canape d'angle XXL bicolore orange et blanc pour grands salons. Assise tres profonde et structure bois massif renforcee. Design moderne bicolore pour caracteriser votre espace.",
    features: ["Simili cuir orange et blanc bicolore","Configuration en L grands espaces","Assise profonde tres confortable","Structure bois massif renforcee","Coussins dossier amovibles"],
    dimensions: "260x220x85cm environ",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-01",
    name: "Ventilateur Continental 18 pouces FS45-308R Telecommande",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 32000, oldPrice: 40000,
    badge: "Promo Chaleur", badgeType: "sale",
    rating: 4.9, reviewsCount: 67,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.51.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.51.jpeg",
    shortDesc: "Continental 18 pouces 450mm avec telecommande, affichage LED, timer et 3 vitesses.",
    description: "Ventilateur sur pied Continental FS45-308R 18 pouces avec telecommande infrarouge. Affichage numerique LED integre, timer programmable 1-8h, 3 vitesses et oscillation automatique. Grand stock disponible en magasin.",
    features: ["Diametre 18 pouces (450mm) fort debit","Telecommande infrarouge incluse","Affichage LED numerique colonne","Timer programmable 1-8 heures","Oscillation automatique 90 degres"],
    dimensions: "Diametre: 450mm | Hauteur max: 135cm | Puissance: 60W",
    stockStatus: "Grand stock en magasin", inStock: true
  },
  {
    id: "yfk-fan-02",
    name: "Ventilateur Lux Fan Blanc 18 pouces Telecommande LED",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 28500, oldPrice: 36000,
    badge: "Silencieux", badgeType: "sale",
    rating: 4.8, reviewsCount: 45,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.28.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.33.jpeg",
    shortDesc: "Lux Fan blanc 5 pales AS, base ronde moderne, telecommande et affichage LED.",
    description: "Ventilateur Lux Fan blanc au design epure. 5 pales AS profilees pour souffle puissant et silencieux. Base ronde elegante avec affichage LED numerique. Telecommande incluse.",
    features: ["5 pales AS aerodynamiques","Base ronde moderne stable","Affichage LED numerique","Telecommande incluse","Oscillation automatique minuterie"],
    dimensions: "Diametre: 450mm | Hauteur max: 135cm | 3 vitesses",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-03",
    name: "Ventilateur Qualia FS219 16 pouces Stand Fan",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 24000, oldPrice: 30000,
    badge: "Puissant", badgeType: "hot",
    rating: 4.7, reviewsCount: 39,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.29.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.29.jpeg",
    shortDesc: "Qualia FS219 moteur haute qualite durable, grille plastique, 3 vitesses et telecommande.",
    description: "Ventilateur Qualia FS219 16 pouces. Moteur haute qualite tres durable, 7 pales PP maximum rendement. Certifie ISO9001. Telecommande incluse.",
    features: ["Moteur haute qualite durable longue vie","Grille plastique PC solide","7 pales PP fort debit d'air","3 vitesses reglables","Certifie ISO9001"],
    dimensions: "Diametre: 400mm | Hauteur max: 125cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-04",
    name: "Ventilateur Oceanic Noir 16 pouces Base Ronde",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 22000, oldPrice: 28000,
    badge: "Economique", badgeType: "sale",
    rating: 4.6, reviewsCount: 55,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.30.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.30.jpeg",
    shortDesc: "Oceanic noir 5 pales blanches base ronde antiderapante, 3 vitesses et oscillation.",
    description: "Ventilateur Oceanic noir avec 5 grandes pales blanches. Base ronde noire antiderapante. Oscillation automatique 90 degres. Parfait pour chambre, bureau ou salon.",
    features: ["5 grandes pales blanches puissantes","Base ronde antiderapante","3 vitesses de soufflage","Oscillation automatique 90 degres","Mat telescopique reglable"],
    dimensions: "Diametre: 400mm | Hauteur max: 130cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-05",
    name: "Ventilateur Continental 16 pouces Stand Fan Noir",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 26000, oldPrice: 33000,
    badge: "Continental", badgeType: "hot",
    rating: 4.8, reviewsCount: 42,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.30 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.30 (2).jpeg",
    shortDesc: "Continental 16 pouces 406mm moteur silencieux design elegant telecommande.",
    description: "Ventilateur Continental 16 pouces design sobre et elegant. Moteur silencieux basse consommation. Base ovale tres stable. Affichage LED. Telecommande infrarouge incluse.",
    features: ["Moteur Continental silencieux fiable","Affichage LED integre","Telecommande infrarouge","Base ovale tres stable","MÃ¢t telescopique reglable"],
    dimensions: "Diametre: 406mm | Puissance: 55W | Hauteur max: 125cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-06",
    name: "Ventilateur Lux Fan Blanc 18 pouces 8 Pales Numerique",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 30000, oldPrice: 38000,
    badge: "Silencieux+", badgeType: "premium",
    rating: 4.9, reviewsCount: 33,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.33.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.33.jpeg",
    shortDesc: "Lux Fan 18 pouces 8 pales semi-transparentes bleues, panneau LED digital base ronde.",
    description: "Ventilateur premium Lux Fan 18 pouces 8 pales semi-transparentes bleues. Souffle exceptionnel et silencieux. Panneau LED digital. Base large ronde ultra-stable.",
    features: ["8 pales semi-transparentes bleues","Souffle puissant et silencieux","Panneau LED digital","Base circulaire extra large","Minuterie et oscillation automatique"],
    dimensions: "Diametre: 450mm | Hauteur max: 140cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-clim-01",
    name: "Climatiseur ASTECH CertiTube Split 100% Cuivre",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 350000, oldPrice: 420000,
    badge: "Neuf", badgeType: "new",
    rating: 4.9, reviewsCount: 18,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.32 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.32 (2).jpeg",
    shortDesc: "ASTECH split 13000 BTU 100% cuivre CertiTube A++ ecologique R410A avec telecommande.",
    description: "Climatiseur split ASTECH certifie CertiTube 100% cuivre. Classe energetique A++. Gaz R410A ecologique. Unite interieure silencieuse et unite exterieure compacte. Telecommande LCD.",
    features: ["100% cuivre CertiTube garantie 5 ans","Classe A++ tres economique","Gaz R410A ecologique sans CFC","Filtre anti-poussiere antibacterien","Telecommande LCD mode sommeil"],
    dimensions: "Unite interieure: 80x20x28cm | 13000 BTU",
    stockStatus: "En stock magasin (Installation sur devis)", inStock: true
  },
  {
    id: "yfk-arm-01",
    name: "Armoire 3 Portes Bois Sculpte avec Miroir Central",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 280000, oldPrice: 340000,
    badge: "Classique", badgeType: "hot",
    rating: 4.9, reviewsCount: 29,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.27 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.27 (1).jpeg",
    shortDesc: "Armoire 3 portes bois sculpte avec miroir pleine longueur central et poignees laiton dore.",
    description: "Grande armoire 3 portes bois massif sculpte avec motifs decoratifs. Porte centrale integre miroir pleine longueur. Poignees dorees laiton. Penderie, etageres et tiroirs interieurs.",
    features: ["Bois massif tres robuste","Motifs sculptes decoratifs","Miroir pleine longueur porte centrale","Poignees laiton dore","Penderie + etageres + tiroirs"],
    dimensions: "Largeur: 150cm | Hauteur: 190cm | Profondeur: 55cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-arm-02",
    name: "Armoire 4 Portes Bois avec 2 Miroirs et Tiroirs",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 360000, oldPrice: 430000,
    badge: "Grande Famille", badgeType: "premium",
    rating: 4.8, reviewsCount: 21,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.45 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.45 (2).jpeg",
    shortDesc: "Grande armoire 4 portes bois teinte avec 2 miroirs centraux et 2 grands tiroirs en bas.",
    description: "Armoire 4 portes grande capacite bois teinte roux. 2 miroirs pleine longueur integres sur portes centrales. 2 grands tiroirs en bas. Espace interieur genereux. Construction solide.",
    features: ["4 portes bois massif","2 miroirs pleine longueur","2 grands tiroirs bas","Espace interieur tres genereux","Joints coulissants metal"],
    dimensions: "Largeur: 200cm | Hauteur: 200cm | Profondeur: 55cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-arm-03",
    name: "Armoire 2 Portes Bois avec Miroir et Tiroir",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 180000, oldPrice: 220000,
    badge: "Compact", badgeType: "sale",
    rating: 4.7, reviewsCount: 34,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.44 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.44 (2).jpeg",
    shortDesc: "Armoire 2 portes bois rainure, miroir porte droite, tiroir central serrure, poignees dorees.",
    description: "Armoire 2 portes compacte bois rainure teinte roux. Miroir pleine longueur integre. Tiroir central avec serrure. Poignees dorees elegantes. Ideale chambre standard.",
    features: ["Bois rainure style classique","Miroir pleine longueur","Tiroir central avec serrure","Poignees dorees laiton","Penderie + etageres"],
    dimensions: "Largeur: 100cm | Hauteur: 200cm | Profondeur: 55cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-lit-01",
    name: "Lit Metal Blanc Capitonne Tete de Lit Romantique",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 195000, oldPrice: 240000,
    badge: "Romantique", badgeType: "premium",
    rating: 4.9, reviewsCount: 24,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.44 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.44 (1).jpeg",
    shortDesc: "Lit metal chrome blanc, tete et pied de lit capitonnes simili cuir blanc avec clous chromes.",
    description: "Lit romantique metal chrome blanc avec tete de lit capitonnee simili cuir blanc. Clous decoratifs chromes. Pied de lit rembourre assorti. Pieds fuseaux chromes elegants.",
    features: ["Structure metal chrome blanc","Tete capitonnee simili cuir blanc","Pied de lit rembourre assorti","Clous decoratifs chromes","Pieds fuseaux chromes"],
    dimensions: "Disponible: 120x190, 140x190, 160x200, 180x200cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-lit-02",
    name: "Lit Fer Forge Noir Ornements Floraux Medaillons",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 155000, oldPrice: 190000,
    badge: "Artisanal", badgeType: "hot",
    rating: 4.8, reviewsCount: 19,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.38.01.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.38.01.jpeg",
    shortDesc: "Lit fer forge noir, tete ornements floraux et medaillons dores, pieds bois fonce.",
    description: "Beau lit fer forge noir avec ornements floraux sculptes et medaillons dores sur la tete de lit. Pieds support bois massif fonce. Design romantique artisanal intemporel.",
    features: ["Fer forge noir anti-oxydation","Ornements floraux medaillons dores","Pieds bois massif fonce","Design romantique intemporel","Charge max 250kg"],
    dimensions: "Disponible: 120x190, 140x190, 160x200cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-miroir-01",
    name: "Miroir sur Pied Pleine Longueur avec Roulettes",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 55000, oldPrice: 70000,
    badge: "3 Coloris", badgeType: "new",
    rating: 4.9, reviewsCount: 43,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.34.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.34.jpeg",
    shortDesc: "Miroir sur pied pleine longueur cadre metal arrondi roulettes, disponible noir blanc ou rose.",
    description: "Miroir sur pied pleine longueur cadre metal arrondi elegant. Inclinaison reglable. Roulettes en bas pour deplacements faciles. 3 coloris : noir, blanc et rose.",
    features: ["Pleine longueur reflet total","Cadre metal arrondi elegant","Inclinaison reglable","Roulettes de deplacement","3 coloris: Noir / Blanc / Rose"],
    dimensions: "Hauteur: 160cm | Largeur miroir: 50cm",
    stockStatus: "En stock (3 coloris disponibles)", inStock: true
  },
  {
    id: "yfk-mat-01",
    name: "Matelas Orthopedique Royal Confort Toutes Tailles",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 135000, oldPrice: 165000,
    badge: "Garantie 5 Ans", badgeType: "premium",
    rating: 5.0, reviewsCount: 63,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.46 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.46.jpeg",
    shortDesc: "Matelas orthopedique certifie grand stock disponible, soutien parfait colonne vertebrale.",
    description: "Matelas orthopedique qualite hoteliere certifie. Confort exceptionnel avec soutien parfait de la colonne vertebrale. Tissu respirant anti-acariens. Plusieurs tailles disponibles. Livraison a domicile possible.",
    features: ["Label Matelas Orthopedique certifie","Soutien parfait colonne vertebrale","Tissu respirant anti-acariens","Epaisseur genereux confort hotel","Plusieurs tailles disponibles"],
    dimensions: "Disponible: 90x190, 120x190, 140x190, 160x200, 180x200cm",
    stockStatus: "Grand stock magasin (Livraison a domicile)", inStock: true
  },
  {
    id: "yfk-table-01",
    name: "Table a Manger Marbre Gris 6 Chaises Cuir",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 520000, oldPrice: 640000,
    badge: "Complete", badgeType: "hot",
    rating: 5.0, reviewsCount: 26,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.40 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.40 (1).jpeg",
    shortDesc: "Table marbre gris veine 6 places avec 6 chaises simili cuir gris capitonnees pieds metal noir.",
    description: "Magnifique ensemble salle a manger plateau marbre gris veine naturel. Pieds metal noir mat. 6 chaises simili cuir gris capitonnees avec surpiquures. Livre complet pret a l'emploi.",
    features: ["Plateau marbre gris veine naturel","Pieds metal noir mat robustes","6 chaises simili cuir gris","Surpiquures decoratives chaises","Livre complet pret a l'emploi"],
    dimensions: "Table: 160x90x78cm | Chaises: 90x46x48cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-table-02",
    name: "Table a Manger Marbre Blanc 4 Chaises Beige",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 430000, oldPrice: 530000,
    badge: "Elegance", badgeType: "premium",
    rating: 4.9, reviewsCount: 19,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.44.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.44.jpeg",
    shortDesc: "Table marbre blanc 4 places avec 4 chaises simili cuir beige taupe coutures et pieds metal noir.",
    description: "Ensemble salle a manger raffine plateau marbre blanc veines subtiles. 4 chaises elegantes simili cuir beige-taupe coutures decoratives pieds metal noir.",
    features: ["Plateau marbre blanc veines naturelles","Pieds metal noir mat","4 chaises cuir beige capitonnees","Coutures decoratives sur les chaises","Design contemporain universel"],
    dimensions: "Table: 140x80x78cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-table-03",
    name: "Table Pliante Marbre Blanc 70x70 ou 80x80cm",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 35000, oldPrice: 45000,
    badge: "Pratique", badgeType: "sale",
    rating: 4.7, reviewsCount: 48,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.40.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.40.jpeg",
    shortDesc: "Table pliante plateau effet marbre blanc pieds metal blanc, disponible 70x70 ou 80x80.",
    description: "Table pliante pratique plateau bois lamine effet marbre blanc. Pieds metal blanc systeme pliage rapide. Ideale petits espaces, terrasse ou cuisine.",
    features: ["Plateau effet marbre blanc elegant","Pieds metal blanc solides","Systeme pliage rapide","Tres legere transportable","2 tailles: 70x70 et 80x80cm"],
    dimensions: "70x70x73cm ou 80x80x73cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-table-04",
    name: "Table a Manger Noire 4 Places Pieds Metal",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 120000, oldPrice: 150000,
    badge: "Economique", badgeType: "sale",
    rating: 4.6, reviewsCount: 32,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.53.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.53.jpeg",
    shortDesc: "Table noire 4 places avec bords blanc pieds metal fin, vendue avec 4 chaises assorties.",
    description: "Table a manger noire lisere blanc sur les bords, legere et facile d'entretien. Vendue avec 4 chaises assorties. Ideale petite cuisine ou salle a manger.",
    features: ["Plateau lamine noir bords blancs","Pieds fins metal noir","Tres legere facile d'entretien","Vendu avec 4 chaises","Ideale petits espaces"],
    dimensions: "Table: 120x70x75cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-tv-01",
    name: "Meuble TV Blanc Elegant 180cm 2 Portes Etageres",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 120000, oldPrice: 150000,
    badge: "Moderne", badgeType: "premium",
    rating: 4.9, reviewsCount: 37,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.42.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.42.jpeg",
    shortDesc: "Meuble TV blanc 180cm 2 portes centrales etageres laterales dessus arrondi elegant.",
    description: "Grand meuble TV blanc 180cm avec 2 portes centrales, etageres laterales ouvertes et plateau superieur arrondi. Pour TV jusqu'a 75 pouces. Design intemporel.",
    features: ["Largeur 180cm TV jusqu'a 75 pouces","2 portes centrales poignees metal","Etageres laterales ouvertes","Dessus plateau arrondi","Pieds bois blancs"],
    dimensions: "180x30x40cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-tv-02",
    name: "Meuble TV Blanc Marbre 180cm Luxe Tiroirs Pieds Dores",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 145000, oldPrice: 180000,
    badge: "Prestige", badgeType: "premium",
    rating: 5.0, reviewsCount: 21,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.39 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.39 (2).jpeg",
    shortDesc: "Meuble TV blanc effet marbre 180cm 4 tiroirs 1 porte poignees dorees pieds acier dore.",
    description: "Meuble TV luxe blanc effet marbre. 4 tiroirs et 1 porte centrale. Poignees metal dore. Pieds fins acier dore 15cm. Design contemporain haut de gamme qui transforme votre salon.",
    features: ["Finition blanc effet marbre luxueux","4 tiroirs poignees dorees","1 porte centrale rangement","Pieds fins acier dore","Compatible TV 80 pouces"],
    dimensions: "180x40x40cm | Pieds: 15cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-tv-03",
    name: "Meuble TV Noir et Blanc 160cm Tiroirs Portes",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 98000, oldPrice: 125000,
    badge: "Bicolore", badgeType: "hot",
    rating: 4.7, reviewsCount: 28,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.42 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.42 (2).jpeg",
    shortDesc: "Meuble TV bicolore noir blanc 160cm avec 2 tiroirs 1 porte etageres ouvertes poignees rondes dorees.",
    description: "Meuble TV bicolore noir et blanc 160cm. 2 tiroirs, 1 porte et etageres ouvertes pour decodeur. Poignees rondes dorees.",
    features: ["Bicolore noir mat blanc brillant","2 tiroirs larges poignees dorees","1 porte espace decodeur","Etageres ouvertes laterales","TV jusqu'a 70 pouces"],
    dimensions: "160x35x40cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-tv-04",
    name: "Meuble TV Bois Naturel et Blanc 180cm Style Cottage",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 110000, oldPrice: 138000,
    badge: "Nature", badgeType: "new",
    rating: 4.8, reviewsCount: 23,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.41 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.41 (2).jpeg",
    shortDesc: "Meuble TV bois naturel et blanc style campagne cottage 2 portes panneaux etageres laterales.",
    description: "Meuble TV style campagne chic bois naturel et blanc casse. 2 portes panneaux mouldres style cottage. Etageres laterales. Tres chaleureux dans un interieur naturel.",
    features: ["Finition bois naturel blanc casse","2 portes panneaux style cottage","Etageres laterales decoratives","Design campagne chic tendance","Pieds bois integres"],
    dimensions: "180x30x40cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-01",
    name: "Bibliotheque Vitree 3 Colonnes Bois Fonce",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 220000, oldPrice: 270000,
    badge: "Bureau", badgeType: "premium",
    rating: 4.9, reviewsCount: 17,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.36 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.36 (1).jpeg",
    shortDesc: "Bibliotheque vitree professionnelle 3 colonnes, portes vitrees haut et bois bas avec serrures.",
    description: "Grande bibliotheque vitree professionnelle 3 colonnes bois fonce. Portes vitrees haut pour livres et deco. Portes bois fermant avec serrure en bas. Cadres metal argente.",
    features: ["3 colonnes portes vitrees haut","3 portes bois bas avec serrure","Cadres metal argente","Etageres interieures reglables","Grande capacite rangement"],
    dimensions: "Largeur: 120cm | Hauteur: 180cm | Profondeur: 35cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-02",
    name: "Meuble Rangement VitrÃ© 2 Portes Fumee Bois Gris",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 150000, oldPrice: 185000,
    badge: "Modulable", badgeType: "hot",
    rating: 4.7, reviewsCount: 24,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.36 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.36 (2).jpeg",
    shortDesc: "Meuble rangement 2 portes vitrees fumees haut et 2 portes bois gris bas, poignees metal noir.",
    description: "Meuble rangement avec 2 portes vitrees fumees partie haute et 2 portes bois gris texture en bas. Poignees metal noir mat. Serrure bas.",
    features: ["2 portes vitrees fumees partie haute","2 portes bois gris partie basse","Poignees metal noir mat","Serrure integree partie basse","Finition gris texture moderne"],
    dimensions: "Largeur: 80cm | Hauteur: 180cm | Profondeur: 35cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-03",
    name: "Meuble Micro-Ondes Bois 2 Niveaux avec Tiroir",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 55000, oldPrice: 70000,
    badge: "Cuisine", badgeType: "new",
    rating: 4.8, reviewsCount: 41,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.33 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.33 (1).jpeg",
    shortDesc: "Meuble cuisine bois 2 niveaux plateau inox chrome en haut tiroir serrure et 2 portes bois.",
    description: "Meuble cuisine ou micro-ondes bois 2 niveaux. Plateau superieur bordure inox chromee pour micro-ondes. Etagere intermediaire. Tiroir avec serrure. 2 portes bois bas.",
    features: ["Plateau superieur bordure inox chromee","Etagere intermediaire","Tiroir avec serrure","2 portes bois bas","Pieds metal noirs"],
    dimensions: "60x45x90cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-04",
    name: "Table Basse Design S Marbre Blanc Metal Noir",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 65000, oldPrice: 82000,
    badge: "Design", badgeType: "premium",
    rating: 5.0, reviewsCount: 33,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.41 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.41 (1).jpeg",
    shortDesc: "Table basse design S double plateau rond effet marbre blanc et structure metal noir.",
    description: "Table basse contemporaine en forme de S. Structure metal noir mat. Double plateau circulaire effet marbre blanc. Piece de design spectaculaire pour votre salon.",
    features: ["Structure metal noir mat en S","2 plateaux ronds effet marbre blanc","Design sculptural contemporain","Plateau bas pour livres","Tres stable et solide"],
    dimensions: "Diametre: 50cm | Hauteur: 60cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-05",
    name: "Table Basse Ronde 3 Niveaux Bois Noyer Metal Noir",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 45000, oldPrice: 58000,
    badge: "Deco", badgeType: "hot",
    rating: 4.7, reviewsCount: 28,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.43 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.43 (1).jpeg",
    shortDesc: "Table d'appoint 3 niveaux ronds bois noyer fonce pieds metal noir courbes tres elegant.",
    description: "Table d'appoint elegante 3 niveaux ronds bois teinte noyer fonce. Pieds courbes metal noir. Ideale table chevet, table d'appoint salon ou presentoir plantes.",
    features: ["3 niveaux ronds progressifs","Bois teinte noyer fonce","Pieds courbes metal noir","Ideale chevet ou d'appoint","Tres stable et legere"],
    dimensions: "Hauteur: 80cm | Diametre grand plateau: 45cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-velo-01",
    name: "Velo Enfant Sport Kuwantong 20 Pouces Noir Rouge",
    category: "sport", categoryLabel: "Velos & Sport",
    price: 95000, oldPrice: 120000,
    badge: "Sport Junior", badgeType: "hot",
    rating: 4.8, reviewsCount: 22,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.59.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.59.jpeg",
    shortDesc: "Velo sport 20 pouces Kuwantong noir rouge, fourche suspension et freins a disque avant arriere.",
    description: "Velo sport junior Kuwantong 20 pouces. Fourche avant avec suspension. Freins a disque avant et arriere. Pneus larges KWTC grande adherence. Pour enfants 8-14 ans.",
    features: ["Cadre acier rouge noir resistant","Fourche avant suspension","Freins disque avant et arriere","Pneus larges KWTC haute adherence","Guidon reglable hauteur"],
    dimensions: "Pour enfants 8-14 ans | Roue: 20 pouces",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-velo-02",
    name: "Velo Enfant MTB Huitong 16 Pouces avec Stabilisateurs",
    category: "sport", categoryLabel: "Velos & Sport",
    price: 65000, oldPrice: 82000,
    badge: "Enfants 3-7 ans", badgeType: "new",
    rating: 4.9, reviewsCount: 31,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.38.02.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.38.02.jpeg",
    shortDesc: "Velo enfant 16 pouces Huitong avec stabilisateurs lateraux garde-boue et gourde incluse.",
    description: "Velo enfant MTB Huitong 16 pouces pour les 3 a 7 ans. Stabilisateurs lateraux, garde-boue avant et arriere, gourde incluse avec porte-bidon. Suspension avant. Freins a main fiables.",
    features: ["Stabilisateurs lateraux apprentissage","Garde-boue avant et arriere","Gourde + porte-bidon inclus","Suspension avant amortisseur","Freins a main ergonomiques"],
    dimensions: "Pour enfants 3-7 ans | Roue: 16 pouces",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chaise-01",
    name: "Chaises Blanches Monobloc Plastique Rigide - Spécial Événements & Cérémonies",
    category: "mobilier", categoryLabel: "Chaises & Événementiel",
    price: 6500, oldPrice: 8500,
    badge: "Grand Arrivage", badgeType: "hot",
    rating: 5.0, reviewsCount: 46,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.18.39.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.18.39.jpeg",
    shortDesc: "Grand stock de chaises blanches empilables ultra-résistantes pour cérémonies, réceptions, mariages et terrasses.",
    description: "Chaises blanches monoblocs en polypropylène vierge renforcé de première qualité. Conçues spécialement pour les cérémonies, baptêmes, mariages, réceptions, séminaires ou aménagement de terrasses à Dakar. Très robustes, faciles à nettoyer et empilables en grandes colonnes pour un transport et stockage rapides. Résistance éprouvée aux UV et intempéries.",
    features: ["Polypropylène vierge renforcé haute résistance", "Empilable en grandes colonnes pour transport et rangement aisés", "Dossier ergonomique strié aéré anti-transpiration", "Idéal pour réceptions, mariages, baptêmes, conférences et terrasses", "Nettoyage facile et excellente résistance au soleil sénégalais"],
    dimensions: "Hauteur: 82cm | Largeur assise: 44cm | Profondeur: 42cm | Charge max: 150 kg",
    stockStatus: "Grand Stock Magasin Disponible Immédiatement", inStock: true
  },
  {
    id: "yfk-fan-07",
    name: "Ventilateur Mural Qualia Haute Performance avec Télécommande",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 35000, oldPrice: 42000,
    badge: "Mural Silencieux", badgeType: "new",
    rating: 4.8, reviewsCount: 19,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.28 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.28 (2).jpeg",
    shortDesc: "Ventilateur mural Qualia gain de place, idéal salons, chambres et bureaux.",
    description: "Ventilateur mural Qualia puissant et silencieux. Fixation murale solide permettant d'optimiser l'espace au sol. Télécommande infrarouge incluse, 3 vitesses de ventilation et minuterie programmable.",
    features: ["Fixation murale sécurisée gain de place", "Télécommande infrarouge multifonctions", "Moteur cuivre silencieux longue durée", "Oscillation automatique grand angle", "3 vitesses de flux d'air"],
    dimensions: "Diamètre hélice: 40cm (16 pouces) | Puissance: 60W",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-08",
    name: "Ventilateur Oceanic Stand Fan FS219 Grande Puissance",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 32000, oldPrice: 38000,
    badge: "Robuste", badgeType: "premium",
    rating: 4.9, reviewsCount: 24,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.31 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.31 (1).jpeg",
    shortDesc: "Stand Fan Oceanic FS219, moteur cuivre endurant et grille de protection renforcée.",
    description: "Ventilateur sur pied Oceanic modèle FS219. Moteur cuivre grande endurance conçu pour les climats chauds. Hauteur réglable et base circulaire équilibrée anti-vibrations.",
    features: ["Moteur 100% cuivre anti-surchauffe", "Hauteur télescopique réglable", "Grille de sécurité maillage serré", "Base ronde stable anti-chute", "Flux d'air puissant et homogène"],
    dimensions: "Hauteur: 125-140cm | Diamètre: 45cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-09",
    name: "Ventilateur Oceanic FS215 Sur Pied Silencieux",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 29000, oldPrice: 35000,
    badge: "Silencieux", badgeType: "new",
    rating: 4.7, reviewsCount: 16,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.31 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.31 (2).jpeg",
    shortDesc: "Ventilateur sur pied Oceanic FS215 faible consommation, idéal pour chambre à coucher.",
    description: "Ventilateur sur pied Oceanic FS215 très silencieux avec consommation électrique maîtrisée. Idéal pour passer des nuits fraîches dans un calme absolu.",
    features: ["Fonctionnement ultra-silencieux pour la nuit", "Faible consommation d'énergie", "3 niveaux de souffle réglables", "Tête orientable verticalement", "Montage et démontage rapides"],
    dimensions: "Hauteur: 120-135cm | Diamètre: 40cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-fan-10",
    name: "Ventilateur Lux Fan Noir 18 Pouces Base Lourde",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 36000, oldPrice: 44000,
    badge: "Puissant", badgeType: "hot",
    rating: 4.9, reviewsCount: 29,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.30 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.30 (1).jpeg",
    shortDesc: "Ventilateur Lux Fan noir finition mate, grand diamètre 18 pouces et flux puissant.",
    description: "Ventilateur de prestige Lux Fan 18 pouces en noir mat. Conçu pour ventiler de grands salons et espaces ouverts avec une portée de souffle supérieure.",
    features: ["Grand diamètre 18 pouces (45cm)", "Finition noir mat haut de gamme", "Base circulaire lourde anti-basculement", "3 pales aérodynamiques grand débit", "Télécommande sans fil"],
    dimensions: "Hauteur: 130-145cm | Diamètre: 45cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-tv-05",
    name: "Meuble TV Moderne Bois Naturel & Tiroirs V073",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 110000, oldPrice: 135000,
    badge: "Design Bois", badgeType: "premium",
    rating: 4.9, reviewsCount: 18,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.36.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.36.jpeg",
    shortDesc: "Meuble TV moderne 160cm en bois noble avec niches centrales et tiroirs latéraux.",
    description: "Meuble TV moderne modèle V073 en finition bois naturel chaleureux. Dispose de grands tiroirs de rangement et de niches centrales pour décodeur, box internet et console de jeux.",
    features: ["Finition bois texturé anti-rayures", "Passe-câbles intégré à l'arrière", "Tiroirs coulissants fluides", "Piètement surélevé facilitant le nettoyage", "Compatible écrans jusqu'à 65 pouces"],
    dimensions: "Longueur: 160cm | Profondeur: 40cm | Hauteur: 48cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-table-05",
    name: "Table Basse de Salon Plateau Marbre & Métal Noir",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 75000, oldPrice: 90000,
    badge: "Élégance", badgeType: "premium",
    rating: 4.8, reviewsCount: 14,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.50 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.50 (1).jpeg",
    shortDesc: "Table basse contemporaine plateau effet marbre et structure acier noir mat.",
    description: "Table basse de salon au design sobre et élégant. Plateau effet marbre résistant aux taches et aux verres chauds, monté sur un piètement en acier noir traité anti-rouille.",
    features: ["Plateau effet marbre poli résistant", "Structure métallique noire soudée robuste", "Pieds équipés de patins de protection sol", "Design intemporel s'accordant avec tous salons"],
    dimensions: "Dimensions: 100 x 55cm | Hauteur: 45cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-salon-08",
    name: "Salon Compact Cuir & Tissu Confort 2 Places",
    category: "salon", categoryLabel: "Salons & Canapes",
    price: 140000, oldPrice: 175000,
    badge: "Gain de Place", badgeType: "new",
    rating: 4.8, reviewsCount: 12,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.41.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.41.jpeg",
    shortDesc: "Canapé 2 places capitonné compact, idéal pour studios, bureaux ou petits salons.",
    description: "Canapé deux places alliant élégance et compacité. Mousse haute résilience 35 kg/m³ garantissant une assise ferme et durable. Revêtement facile d'entretien.",
    features: ["Assise mousse haute résilience 35 kg/m³", "Structure en bois massif renforcé", "Idéal petits espaces et appartements", "Pieds design robustes"],
    dimensions: "Longueur: 150cm | Profondeur: 85cm | Hauteur: 82cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-arm-04",
    name: "Armoire Battante 3 Portes Bois Modèle Exclusif",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 165000, oldPrice: 195000,
    badge: "Chambre Confort", badgeType: "premium",
    rating: 4.9, reviewsCount: 21,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.45.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.45.jpeg",
    shortDesc: "Armoire 3 portes battantes avec penderie intégrée et étagères spacieuses.",
    description: "Armoire de chambre 3 portes battantes spacieuse. Comporte une zone penderie pour cintres et robes, ainsi que plusieurs compartiments d'étagères et tiroirs pour ranger tout votre linge.",
    features: ["Grand espace penderie + étagères modulables", "Charnières métalliques amorties silencieuses", "Finition bois noble soignée", "Serrures sécurisées avec clés fournies"],
    dimensions: "Largeur: 140cm | Hauteur: 200cm | Profondeur: 52cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-rang-06",
    name: "Meuble Console & Entrée Design Contemporain",
    category: "rangement", categoryLabel: "Meubles TV & Rangement",
    price: 65000, oldPrice: 80000,
    badge: "Décoration", badgeType: "new",
    rating: 4.8, reviewsCount: 17,
    image: IMG + "WhatsApp Image 2026-09-19 at 14.37.53 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 14.37.53 (1).jpeg",
    shortDesc: "Console d'entrée fine et moderne pour poser clés, décoration et accessoires.",
    description: "Meuble console d'entrée moderne pour habiller vos couloirs, entrées ou séjours. Structure fine et résistante apportant une touche de raffinement dès le pas de la porte.",
    features: ["Format étroit gain de place pour couloir et entrée", "Plateau lisse facile d'entretien", "Structure stable en acier thermo-laqué", "Pieds avec patins antidérapants"],
    dimensions: "Longueur: 100cm | Profondeur: 30cm | Hauteur: 75cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-mc201",
    name: "Ensemble Chambre à Coucher Complète de Prestige MC-201#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 580000, oldPrice: 650000,
    badge: "Grand Luxe", badgeType: "premium",
    rating: 5.0, reviewsCount: 38,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.12.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.12.jpeg",
    shortDesc: "Chambre complète de maître avec grand lit tête capitonnée dorée, armoire 6 portes dressing, coiffeuse lumineuse et chevets.",
    description: "Ensemble complet de chambre à coucher haut de gamme modèle MC-201#. Comprend un somptueux grand lit double avec tête de lit capitonnée effet marbre et motifs géométriques dorés, une armoire 6 portes battantes avec miroirs biseautés centraux, une élégante coiffeuse avec miroir lumineux LED et deux tables de chevet assorties.",
    features: ["Grand lit 2 places avec tête capitonnée et finitions or", "Armoire dressing 6 portes avec miroirs centraux", "Coiffeuse commode avec miroir LED intégré et tiroirs", "2 tables de chevet coordonnées incluses", "Matériaux nobles haute résistance aux finitions impeccables"],
    dimensions: "Lit: 180x200cm | Armoire: 240x210x55cm | Coiffeuse: 120x80x45cm",
    stockStatus: "Disponible en magasin • Grand Mbao", inStock: true
  },
  {
    id: "yfk-chambre-mc202",
    name: "Ensemble Chambre Complète Gris Anthracite & Or MC-202#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 590000, oldPrice: 670000,
    badge: "Design Royal", badgeType: "premium",
    rating: 4.9, reviewsCount: 29,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.13.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.13.jpeg",
    shortDesc: "Chambre complète contemporaine gris anthracite et liserés dorés avec armoire 6 portes et coiffeuse miroir LED.",
    description: "Chambre à coucher contemporaine d'exception MC-202#. Teinte gris anthracite moderne rehaussée de profils et dorures chaleureuses. Comprend un lit king size avec tête de lit rainurée velours, une armoire 6 portes avec miroirs centraux, une commode coiffeuse avec grand miroir lumineux et ses 2 chevets.",
    features: ["Finition gris anthracite satiné & or brossé", "Armoire 6 portes grand volume penderie + étagères", "Lit king size avec dossier matelassé ultra-confort", "Coiffeuse avec miroir rétroéclairé et multiples tiroirs", "Structure robuste anti-rayures"],
    dimensions: "Lit: 180x200cm | Armoire: 240x220x60cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-203",
    name: "Chambre à Coucher Majestueuse Blanc Crème & Dorures Royales 203#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 620000, oldPrice: 710000,
    badge: "Édition Palais", badgeType: "premium",
    rating: 5.0, reviewsCount: 34,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (1).jpeg",
    shortDesc: "Ensemble chambre blanc crème et rosaces dorées avec lit capitonné, armoire 6 portes, coiffeuse et tabouret.",
    description: "Chambre à coucher royale modèle 203#. Teinte blanc crème lumineux ornée de médaillons et motifs orientaux dorés. Ensemble complet comprenant le lit capitonné 2 places, la grande armoire 6 portes à miroirs, la coiffeuse avec tabouret rembourré et les deux chevets latéraux.",
    features: ["Médaillons et arabesques dorées gravées", "Lit capitonné avec éclairage intégré à la tête", "Armoire 6 portes grand volume avec penderie intégrée", "Coiffeuse avec tabouret assorti et compartiments cosmétiques", "Finition laquée facile à nettoyer"],
    dimensions: "Lit: 180x200cm | Armoire: 240x215x55cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-mc632",
    name: "Ensemble Chambre de Maître Chêne Naturel & Blanc Laqué MC-632#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 610000, oldPrice: 690000,
    badge: "LED Intégré", badgeType: "hot",
    rating: 4.9, reviewsCount: 27,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (2).jpeg",
    shortDesc: "Chambre chêne naturel et blanc laqué avec tête de lit lumineuse LED, armoire 6 portes et tiroirs bijoux.",
    description: "Chambre à coucher haut de gamme MC-632# alliant la chaleur du chêne naturel et l'éclat du blanc laqué rehaussé de doré. Tête de lit sculptée avec ruban LED lumineux intégré, grande armoire 6 portes avec miroirs, commode coiffeuse avec tiroir à compartiments velours pour montres et bijoux.",
    features: ["Éclairage d'ambiance LED intégré sur la tête de lit", "Tiroir spécial velours rouge compartimenté pour montres/bijoux", "Armoire 6 portes dressing intérieur complet", "Bois robuste traité contre l'humidité", "Design raffiné et intemporel"],
    dimensions: "Lit: 180x200cm | Armoire: 240x215x58cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-mc920",
    name: "Chambre de Luxe Noire & Or Impérial MC-920#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 650000, oldPrice: 750000,
    badge: "Exclusif Showroom", badgeType: "premium",
    rating: 5.0, reviewsCount: 42,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (3).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (3).jpeg",
    shortDesc: "Chambre complète noire et or impérial avec lit à appliques lumineuses intégrées, armoire 6 portes et miroir tactile.",
    description: "Modèle prestige MC-920#. Finition noir profond et dorures impériales. Lit monumental avec appliques lumineuses intégrées de chaque côté de la tête de lit, armoire 6 portes battantes avec miroirs centraux et claustras dorés, meuble coiffeuse avec grand miroir à rétroéclairage LED tactile.",
    features: ["Appliques lumineuses chaleureuses intégrées à la tête de lit", "Miroir de coiffeuse à éclairage LED tactile", "Claustras et décors dorés en relief", "Armoire 6 portes panoramique", "Chevet 2 tiroirs avec poignées cristal/or"],
    dimensions: "Lit: 180x200cm | Armoire: 245x220x60cm",
    stockStatus: "Exposé au Showroom de Grand Mbao", inStock: true
  },
  {
    id: "yfk-chambre-mc634",
    name: "Ensemble Chambre de Prestige Blanc Marbré & Or MC-634#",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 630000, oldPrice: 720000,
    badge: "Prestige", badgeType: "hot",
    rating: 4.9, reviewsCount: 31,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (4).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.13 (4).jpeg",
    shortDesc: "Chambre blanc marbré avec arches dorées lumineuses sur lit et armoire, buffet coiffeuse moderne.",
    description: "Chambre à coucher moderne de prestige MC-634#. Harmonie de blanc marbré, chêne clair et dorures galbées. La tête de lit et l'armoire arborent des arches dorées avec rétroéclairage LED créant une ambiance de palace. Coiffeuse buffet moderne avec grand miroir carré lumineux.",
    features: ["Arches dorées avec éclairage LED d'ambiance", "Façades blanches marbrées brillantes", "Armoire 6 portes avec vitrines miroir biseauté", "Grande coiffeuse buffet avec rangements fermés", "Lit coffre robuste à grande capacité"],
    dimensions: "Lit: 180x200cm | Armoire: 240x220x58cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-zs528",
    name: "Chambre Royale d'Apparat ZS-528# avec 2 Fauteuils de Lit",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 750000, oldPrice: 850000,
    badge: "Chef d'Œuvre", badgeType: "premium",
    rating: 5.0, reviewsCount: 52,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.14.jpeg",
    shortDesc: "Suite complète de salon d'apparat avec 2 fauteuils de lit assortis, armoire d'angle panoramique or et coiffeuse royale.",
    description: "Le modèle suprême de notre collection ZS-528#. Suite de chambre royale avec lit king size orné d'arches dorées et appliques de chevet, accompagnée de ses 2 fauteuils velours blancs de bout de lit avec chevet central. Armoire monumentale galbée avec miroirs or teinté et bande LED au sol. Meuble coiffeuse de reine avec miroirs multiples.",
    features: ["Inclus 2 fauteuils de bout de lit velours blanc + chevet central", "Armoire monumentale galbée avec éclairages LED intégrés au sol", "Miroirs teintés bronze et dorures impériales", "Grande coiffeuse avec multiples miroirs de maquillage", "Finitions artisanales d'une beauté exceptionnelle"],
    dimensions: "Lit king size 200x200cm | Armoire panoramique: 280x225x60cm",
    stockStatus: "Pièce Maîtresse Showroom Grand Mbao", inStock: true
  },
  {
    id: "yfk-chambre-zs529",
    name: "Suite Parentale Palais Blanc & Doré ZS-529# avec Lustres Intégrés",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 730000, oldPrice: 820000,
    badge: "Lustres Cristal", badgeType: "premium",
    rating: 5.0, reviewsCount: 45,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (1).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (1).jpeg",
    shortDesc: "Chambre de palais avec véritables lustres cristal suspendus intégrés à la tête de lit et armoire galbée lumineuse.",
    description: "Modèle féerique ZS-529#. Véritable suite digne des plus grands palais. Tête de lit matelassée de 3 mètres de large intégrant deux véritables lustres en cascade de cristal doré. Grande armoire galbée 6 portes avec rétroéclairage doré au sol et coiffeuse majestueuse multi-niveaux.",
    features: ["2 vrais lustres en cascade de cristal doré intégrés à la tête de lit", "Bandeau lumineux doré continu à la base des meubles", "Armoire à portes galbées et grands miroirs d'essayage", "Coiffeuse géante avec vitrines et tiroirs capitonnés", "Revêtement blanc matelassé capitonné de très grand luxe"],
    dimensions: "Tête de lit largeur 300cm | Lit 180x200cm | Armoire: 260x220x60cm",
    stockStatus: "Exposé au Showroom • Grand Mbao", inStock: true
  },
  {
    id: "yfk-chambre-zs518",
    name: "Chambre Grand Standing Coquille Bouclette & Or ZS-518# (Zhuo Sheng)",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 680000, oldPrice: 780000,
    badge: "Tendance 2026", badgeType: "hot",
    rating: 4.9, reviewsCount: 39,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (2).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (2).jpeg",
    shortDesc: "Lit rond coquille d'huître en velours bouclette avec rétroéclairage circulaire, armoire dressing verre bronze.",
    description: "Création design Zhuo Sheng modèle ZS-518#. Lit architectural avec tête de lit circulaire en forme de coquille d'huître en tissu bouclette blanc texturé et anneau doré rétroéclairé. Armoire dressing moderne avec portes en verre bronze fumé translucide et coiffeuse design contemporain.",
    features: ["Tête de lit circulaire coquille d'huître en bouclette blanche", "Anneau doré avec halo lumineux LED d'ambiance", "Armoire dressing contemporaine avec portes verre bronze fumé", "Coiffeuse géométrique avec grand miroir hexagonal", "Bout de lit rembourré arrondi ultra-tendance"],
    dimensions: "Lit: 180x200cm | Armoire: 240x220x60cm",
    stockStatus: "En stock magasin", inStock: true
  },
  {
    id: "yfk-chambre-zs519",
    name: "Chambre Majesté Gris Nacré & Or Rose ZS-519# avec Banc Coffre",
    category: "chambre", categoryLabel: "Chambres & Armoires",
    price: 690000, oldPrice: 790000,
    badge: "Banc Inclus", badgeType: "premium",
    rating: 5.0, reviewsCount: 36,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (3).jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (3).jpeg",
    shortDesc: "Ensemble gris nacré & or rose avec coffre banc de bout de lit, armoire miroir ovale et grand miroir psyché supplémentaire.",
    description: "Modèle grand standing ZS-519#. Teinte gris nacré métallisée associée à l'or rose. Lit king size avec grand coffre-banc de bout de lit rembourré assorti pour ranger couettes et coussins. Armoire 6 portes avec miroir central ovale, meuble coiffeuse hollywoodienne et un grand miroir psyché vertical sur pied coordonné.",
    features: ["Inclus : grand coffre-banc de bout de lit assorti", "Inclus : grand miroir psyché vertical sur pied supplémentaire", "Finitions précieuses gris nacré et or rose", "Armoire dressing avec miroir central ovale", "Coiffeuse avec éclairage contour LED"],
    dimensions: "Lit: 180x200cm | Armoire: 250x220x60cm | Banc: 140x45x45cm",
    stockStatus: "En stock magasin • Grand Mbao", inStock: true
  },
  {
    id: "yfk-banc-01",
    name: "Poutre Banc Salle d'Attente 4 Places Métal & Cuir PVC (Réf: A204-1)",
    category: "mobilier", categoryLabel: "Chaises & Bureaux",
    price: 135000, oldPrice: 165000,
    badge: "Attente 4 Places", badgeType: "new",
    rating: 4.9, reviewsCount: 23,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.15.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.15.jpeg",
    shortDesc: "Banc poutre 4 places assises métal argenté avec coussins d'assise et dossiers en cuir PVC noir matelassé.",
    description: "Banc poutre d'attente 4 places modèle A204-1 conçu pour un usage intensif dans les salles d'attente d'hôpitaux, cliniques médicales, agences bancaires, cabinets d'avocats, aéroports et halls de réception à Dakar. Poutre et pieds en acier perforé robuste peints en gris argenté thermo-laqué. Assises et dossiers équipés de coussins grand confort en cuir PVC noir haute densité résistant et lavable. Accoudoirs latéraux chromés confortables.",
    features: ["4 places assises confortables avec accoudoirs d'extrémité chromés", "Coussins d'assise et dossier rembourrés en cuir PVC noir ultra-résistant", "Structure poutre acier épais thermo-laqué anti-corrosion", "Pieds stables avec patins réglables anti-rayures pour carrelage", "Facile à désinfecter et entretenir au quotidien"],
    dimensions: "Longueur totale: 230cm | Profondeur: 68cm | Hauteur dossier: 78cm",
    stockStatus: "En stock magasin • Idéal Professionnels & Cliniques", inStock: true
  },
  {
    id: "yfk-banc-02",
    name: "Poutre Banc Salle d'Attente 3 Places Métal & Cuir PVC (Réf: A203-1)",
    category: "mobilier", categoryLabel: "Chaises & Bureaux",
    price: 110000, oldPrice: 135000,
    badge: "Attente 3 Places", badgeType: "hot",
    rating: 4.8, reviewsCount: 19,
    image: IMG + "WhatsApp Image 2026-09-20 at 00.35.16.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-20 at 00.35.16.jpeg",
    shortDesc: "Banc poutre 3 places assises métal gris argenté avec coussins en cuir PVC noir pour accueil et bureaux.",
    description: "Banc poutre d'accueil 3 places assises modèle A203-1. Parfaitement adapté pour les accueils d'entreprises, cabinets médicaux, études notariales ou secrétariats. Structure métallique robuste couleur aluminium gris argenté avec 3 assises ergonomiques rembourrées en cuir PVC noir anti-tache et accoudoirs profilés.",
    features: ["3 places assises ergonomiques avec rembourrage cuir PVC noir", "Poutre acier renforcé haute capacité de charge", "Accoudoirs profilés confortables", "Patins de sol réglables pour parfaite stabilité", "Nettoyage rapide résistant aux produits d'entretien"],
    dimensions: "Longueur totale: 175cm | Profondeur: 68cm | Hauteur dossier: 78cm",
    stockStatus: "En stock magasin • Disponible Immédiatement", inStock: true
  },
  {
    id: "yfk-table-ocre-04",
    name: "Ensemble Table Pliante & 4 Fauteuils Terrasse Ocre",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 65000, oldPrice: 80000,
    badge: "Terrasse & Jardin", badgeType: "new",
    rating: 4.8, reviewsCount: 15,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.15.22.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.15.22.jpeg",
    shortDesc: "Ensemble table pliante avec plateau renforcé ocre et 4 fauteuils confortables à pieds métal.",
    description: "Ensemble complet d'extérieur ou intérieur composé d'une table rectangulaire pliable et de 4 fauteuils ergonomiques couleur ocre/caramel. Matériau plastique haute densité traité anti-UV et intempéries avec pieds tubulaires en métal renforcé. Idéal pour terrasse, balcon, jardin ou salle à manger décontractée.",
    features: ["Table rectangulaire pliable facilement transportable et rangeable", "4 fauteuils ergonomiques avec accoudoirs confortables", "Structure pieds métal résistant et plastique anti-UV", "Trou central pour parasol", "Nettoyage facile à l'eau et au savon"],
    dimensions: "Table: 120 x 70cm | Hauteur: 75cm",
    stockStatus: "En stock magasin • Grand Mbao", inStock: true
  },
  {
    id: "yfk-table-traiteur-01",
    name: "Grande Table Pliante Traiteur 8-10 Places HDPE Blanche",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 48000, oldPrice: 60000,
    badge: "Format Valise", badgeType: "hot",
    rating: 4.9, reviewsCount: 31,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.15.24.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.15.24.jpeg",
    shortDesc: "Grande table pliante blanche 180cm polyéthylène haute densité avec poignée valise pour réceptions et cérémonies.",
    description: "Grande table pliante traiteur professionnelle de 180cm (8 à 10 personnes). Plateau en résine polyéthylène haute densité (HDPE) ultra-résistante aux chocs, taches et intempéries. Se plie en deux sous forme de valise compacte avec poignée de transport intégrée. Idéale pour mariages, baptêmes, réceptions, traiteurs, restaurants et réunions de famille.",
    features: ["Capacité 8 à 10 places assises confortables", "Pliable en deux en format valise avec poignée de transport", "Plateau HDPE haute résistance anti-taches et étanche", "Structure pieds acier traité avec bague de verrouillage anti-repli", "Chaises de cérémonie assorties disponibles au magasin"],
    dimensions: "Longueur: 180cm | Largeur: 75cm | Hauteur: 74cm",
    stockStatus: "Grand Stock Disponible Magasin", inStock: true
  },
  {
    id: "yfk-table-blanche-06",
    name: "Ensemble Table à Manger Blanche & 6 Chaises de Réception",
    category: "salle_manger", categoryLabel: "Tables & Salle a Manger",
    price: 70000, oldPrice: 85000,
    badge: "Pack 6 Chaises", badgeType: "new",
    rating: 4.9, reviewsCount: 22,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.15.25.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.15.25.jpeg",
    shortDesc: "Table rectangulaire blanche livrée avec ses 6 chaises assorties pour repas de famille et événements.",
    description: "Pack complet table à manger blanche 6 places accompagnée de 6 chaises monobloc confortables à dossier ajouré. Solution économique, esthétique et durable pour équiper une salle à manger, une cour intérieure, une terrasse ou organiser des réceptions privées.",
    features: ["Table rectangulaire robuste blanche avec film protecteur", "Pack de 6 chaises de réception assorties incluses", "Plastique robuste facile d'entretien et lavable", "Montage rapide et pieds stables", "Idéal pour maisons de famille et réceptions"],
    dimensions: "Table: 140 x 80cm | 6 Chaises ergonomiques",
    stockStatus: "En stock magasin • Prêt à emporter", inStock: true
  },
  {
    id: "yfk-tv-smart-55",
    name: "Smart TV 55\" 4K Ultra HD Frameless Sans Bordure",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 195000, oldPrice: 235000,
    badge: "Smart TV 55\"", badgeType: "hot",
    rating: 5.0, reviewsCount: 44,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.15.49.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.15.49.jpeg",
    shortDesc: "Téléviseur connecté Smart TV 55 pouces (140 cm) 4K UHD avec écran sans bordure, Wi-Fi et applications intégrées.",
    description: "Téléviseur connecté dernière génération Smart TV 55 pouces (140 cm de diagonale) écran Ultra HD 4K résolution 3840x2160. Design Frameless ultra-fin sans bordure offrant une immersion visuelle totale. Équipé du Wi-Fi intégré, accès direct à YouTube, Netflix, Prime Video et navigateur web. Décodeur TNT et récepteur satellite intégrés.",
    features: ["Écran géant 55 pouces (140 cm) 4K Ultra HD HDR", "Design Frameless sans bordure moderne et élégant", "Système Smart TV avec Wi-Fi, YouTube, Netflix, Screen Mirroring", "Décodeur TNT & Satellite intégré", "Connectique complète : HDMI x3, USB x2, Optique, AV"],
    dimensions: "Diagonale: 55 pouces (140cm) | Pieds métal inclus",
    stockStatus: "En stock magasin • Neuf dans carton garanti", inStock: true
  },
  {
    id: "yfk-tv-smart-43",
    name: "Smart TV 43\" Full HD Frameless Slim (Wi-Fi & Dolby Audio)",
    category: "electromenager", categoryLabel: "Ventilateurs & Electro",
    price: 145000, oldPrice: 175000,
    badge: "Frameless Slim", badgeType: "new",
    rating: 4.9, reviewsCount: 28,
    image: IMG + "WhatsApp Image 2026-09-19 at 18.15.50.jpeg",
    storePhoto: IMG + "WhatsApp Image 2026-09-19 at 18.15.50.jpeg",
    shortDesc: "Smart TV 43 pouces (109 cm) design ultra-plat bordeless avec connexion Wi-Fi et son Dolby Audio.",
    description: "Téléviseur Smart TV 43 pouces (109 cm) haute définition avec contours ultra-fins slim frameless. Profitez d'une qualité d'image éclatante et de vos séries préférées grâce aux applications connectées et au Wi-Fi haut débit. Son stéréo surround puissant et clair avec technologie Dolby Audio.",
    features: ["Écran 43 pouces (109 cm) Full HD haute luminosité", "Bordures ultra-fines 'Frameless Slim' modernes", "Smart TV connectée : Wi-Fi, Netflix, YouTube, casting smartphone", "Son stéréo Dolby Audio clair et immersif", "Pieds élégants + compatible support mural VESA"],
    dimensions: "Diagonale: 43 pouces (109cm) | Pieds et télécommande inclus",
    stockStatus: "En stock magasin • Garanti", inStock: true
  }
];

const CATEGORIES = [
  { id: "all", label: "Tous les Rayons", icon: "grid", count: PRODUCTS.length },
  { id: "mobilier", label: "Chaises & Bureaux", icon: "armchair", count: PRODUCTS.filter(p => p.category === "mobilier").length },
  { id: "salon", label: "Salons & Canapes", icon: "sofa", count: PRODUCTS.filter(p => p.category === "salon").length },
  { id: "electromenager", label: "Ventilateurs & Electro", icon: "wind", count: PRODUCTS.filter(p => p.category === "electromenager").length },
  { id: "chambre", label: "Chambres & Armoires", icon: "bed", count: PRODUCTS.filter(p => p.category === "chambre").length },
  { id: "salle_manger", label: "Tables & Salle a Manger", icon: "utensils", count: PRODUCTS.filter(p => p.category === "salle_manger").length },
  { id: "rangement", label: "Meubles TV & Rangement", icon: "tv", count: PRODUCTS.filter(p => p.category === "rangement").length },
  { id: "sport", label: "Velos & Sport", icon: "bike", count: PRODUCTS.filter(p => p.category === "sport").length }
];

const STORE_GALLERY = [
  { title: "Suite Royale ZS-528# en Showroom", subtitle: "Grand lit double avec 2 fauteuils, armoire dorée et commode", image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14.jpeg", type: "real_store", caption: "Exposition suite parentale royale or et blanc en direct du magasin." },
  { title: "Chambre Palais ZS-529# avec Lustres", subtitle: "Tête de lit avec lustres cristal et éclairages d'ambiance", image: IMG + "WhatsApp Image 2026-09-20 at 00.35.14 (1).jpeg", type: "real_store", caption: "Ensemble chambre de maître grand luxe exposé dans notre showroom." },
  { title: "Rayon Salons de Luxe", subtitle: "Chesterfield, cuir gris or, blanc ivoire et plus", image: IMG + "WhatsApp Image 2026-09-19 at 14.37.38.jpeg", type: "real_store", caption: "Notre collection de salons de luxe disponible en magasin." },
  { title: "Rayon Ventilateurs - Grand Stock", subtitle: "Continental, Qualia, Lux Fan, Oceanic disponibles", image: IMG + "WhatsApp Image 2026-09-19 at 14.37.51.jpeg", type: "real_store", caption: "Grand stock ventilateurs toutes marques et tailles." },
  { title: "Salons Gris et Or Modernes", subtitle: "Ensemble cuir gris avec liseret or pieds dores", image: IMG + "WhatsApp Image 2026-09-19 at 14.37.37 (2).jpeg", type: "real_store", caption: "Salons modernes disponibles en livraison immediate." },
  { title: "Tables Marbre Salle a Manger", subtitle: "Marbre gris 6 places ou blanc 4 places", image: IMG + "WhatsApp Image 2026-09-19 at 14.37.40 (1).jpeg", type: "real_store", caption: "Tables repas design plateau marbre et chaises cuir." },
  { title: "Stock Matelas Orthopediques", subtitle: "Grand stock toutes tailles disponible immediatement", image: IMG + "WhatsApp Image 2026-09-19 at 14.37.46 (1).jpeg", type: "real_store", caption: "Matelas orthopediques certifies en grand stock magasin." },
  { title: "Stock Chaises Cérémonies & Réceptions", subtitle: "Piles de chaises blanches neuves en disponibilité immédiate", image: IMG + "WhatsApp Image 2026-09-19 at 18.18.39.jpeg", type: "real_store", caption: "Grand stock de chaises blanches monobloc de réception disponible en direct au magasin à Grand Mbao." }
];
